networks:
  festival.net:
    driver: bridge

services:
  api:
    image: canals/php
    env_file: ./festival.env
    restart: unless-stopped
    volumes:
      - ./app/:/var/www/html/app
    ports:
      - "22000:80"
    networks:
      - festival.net
    depends_on:
      - festival.db


  festival.db:
    image: mariadb:10.3
    env_file: ./festivaldb.env
    volumes:
      - ./data/:/var/lib/mysql
    ports:
      - "22001:3306"
    networks:
      - festival.net
    restart: unless-stopped

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "22002:8080"
    networks:
      - festival.net